[project]
name = "backend"
version = "1.0.0"
description = "Create a application with fastapi and postgres-flexible"
dependencies = [
    "fastapi_app"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
