name: App Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_package:
    name: Test ${{ matrix.os }} Python ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-13", "macos-latest-xlarge", "windows-latest"]
        python_version: ["3.10", "3.11", "3.12"]
        exclude:
          - os: macos-latest-xlarge
            python_version: "3.10"
    steps:
        - uses: actions/checkout@v4
        - name: Check for MacOS Runner
          if: matrix.os == 'macos-latest-xlarge'
          run: brew install postgresql@14
        - name: Install pgvector on Windows using install-pgvector.bat
          if: matrix.os == 'windows-latest'
          shell: cmd
          run: .github\workflows\install-pgvector.bat
        - name: Setup postgres
          uses: ikalnytskyi/action-setup-postgres@v6
          with:
            username: admin
            password: postgres
            database: postgres
        - name: Setup python
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python_version }}
            architecture: x64
        - name: Install dependencies
          run: |
            python -m pip install -r requirements-dev.txt
        - name: Install app as editable app
          run: |
            python -m pip install -e src
        - name: Setup local database with seed data
          run: |
            cp .env.sample .env
            python ./src/fastapi_app/setup_postgres_database.py
            python ./src/fastapi_app/setup_postgres_seeddata.py
